name: Build

on: push

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run tests
        run: ./scripts/run_tests.sh
        
      - name: Upload test artifacts
        uses: actions/upload-artifact@v4
        with:
          name: test-reports
          path: |
            reports/tests/
            reports/coverage/
          retention-days: 1

  docker:
    needs: build
    if: github.ref == 'refs/heads/main'
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Build the Docker image
        run: docker build -t bndeepti/devops-learning:latest .

      - name: Push the Docker image
        run: docker push bndeepti/devops-learning:latest