name: Devops Learning

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: "github-actions"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run tests
        run: pytest