name: Docker

on:
  workflow_run:
    workflows: ["Build"]
    types:
      - completed

jobs:
  docker:
    if: >
      ${{ github.event.workflow_run.conclusion == 'success' &&
          github.event.workflow_run.head_branch == 'main' }}
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Build the Docker image
        run: docker build -t bndeepti/devops-learning:latest .

      - name: Push the Docker image
        run: docker push bndeepti/devops-learning:latest